# File entirely generated by Google Gemini 3 (For more info, see report Section 7.1)

# This script counts the number of .tif mask files in a specified folder 
# that contain any tumor presence (i.e., more than 0 pixels) 
# and those that have tumor coverage between 3% and 3.5%. 
# It prints the results to the console.

import os
import glob
import torch
import numpy as np
import nibabel as nib
import argparse
import random
from torch.utils.data import Dataset
from tqdm import tqdm

root_dir = "/Dataset001_BraTS2023/"
split = 'val'
samples = []

n_tumor = 0
n_no_tumor = 0
n = 0

images_dir = os.path.join(root_dir, "imagesTr")
labels_dir = os.path.join(root_dir, "labelsTr")

print(f"Scanning {root_dir} for volumes...")
image_files = glob.glob(os.path.join(images_dir, "*0003.nii.gz"))
print(f"Found {len(image_files)} image files.")


# Split patients into train/val based on patient ID
patient_ids = set()
for img_path in tqdm(image_files):
    filename = os.path.basename(img_path)
    parts = filename.split('-')
    patient_id = parts[2] 
    trial = parts[3].split('_')[0]  
    patient_ids.add(f"{patient_id}-{trial}")

# Need consistent ordering 
patient_ids = sorted(list(patient_ids))

# Reproducible shuffle
random.Random(1234).shuffle(patient_ids)
n = len(patient_ids)
selected_ids = []

if split == 'train':
    selected_ids = patient_ids[:int(0.8 * n)]
elif split == 'val':
    selected_ids = patient_ids[int(0.8 * n):]
elif split == 'train_2000': # only 2000 images with tumor (0.03 ratio)
    selected_ids = patient_ids[:int(0.55 * n)]
elif split == 'val_tiny':
    selected_ids = patient_ids[int(0.8 * n):int(0.8 * n)+20]
elif split == 'val_small':
    selected_ids = patient_ids[int(0.8 * n):int(0.9 * n)]

for img_path in tqdm(image_files):
    filename = os.path.basename(img_path)
    
    parts = filename.split('-')
    
    # Format: ['BraTS', 'GLI', '00001', '000_0003.nii.gz']
    patient_id = parts[2] 
    trial = parts[3].split('_')[0]  
    
    if f"{patient_id}-{trial}" not in selected_ids:
        continue
    
    label_name = f"BraTS-GLI-{patient_id}-{trial}.nii.gz"
    label_path = os.path.join(labels_dir, label_name)

    if not os.path.exists(label_path):
        continue

    seg_obj = nib.load(label_path)
    seg_data = seg_obj.get_fdata()

    n_slices = 135 
    for slice_idx in range(20, n_slices):
        # if slice_idx < 20 or slice_idx > 134:
        #     continue
        n+= 1

        ratio_tumor = np.sum(seg_data[:, :, slice_idx]) / (seg_data.shape[0] * seg_data.shape[1])
        if "ratio" in split and (ratio_tumor < 0.03 or ratio_tumor > 0.035):
            n_no_tumor += 1
            continue
        elif ratio_tumor == 0:
            n_no_tumor += 1
            continue
        
        n_tumor += 1
        # samples.append({
        #     'image_path': img_path,
        #     'label_path': label_path,
        #     'slice_idx': slice_idx,
        #     'patient_id': f"{patient_id}-{trial}"
        # })
        

print(f"Total slices scanned: {n}")
print(f"Slices with tumor:   {n_tumor}")
print(f"Slices without tumor:{n_no_tumor}")
# print(f"Total slices in dataset: {len(samples)}") 