# File entirely generated by Google Gemini 3 (For more info, see report Section 7.1)

# This script counts the number of .tif mask files in a specified folder 
# that contain any tumor presence (i.e., more than 0 pixels) 
# and those that have tumor coverage between 3% and 3.5%. 
# It prints the results to the console.
import os
import cv2
import numpy as np

def analyze_tumor_masks(folder_path):
    """
    Counts mask files with any tumor presence and those within a specific 
    3% - 3.5% coverage range.
    
    Args:
        folder_path (str): Path to the folder containing .tif mask files.
    """
    
    # Initialize counters
    files_with_tumor_count = 0
    files_in_range_count = 0
    total_tif_files = 0

    # checks if folder exists
    if not os.path.exists(folder_path):
        print(f"Error: The folder '{folder_path}' does not exist.")
        return

    folders = [f for f in os.listdir(folder_path) if os.path.isdir(os.path.join(folder_path, f))]
    print(f"Scanning folder: {folder_path} ...\n")

    for subfolder in folders:
        subfolder_path = os.path.join(folder_path, subfolder)
        print(f"Processing subfolder: {subfolder} ...")
        # Iterate through all files in the directory
        for filename in os.listdir(subfolder_path):
            if filename.lower().endswith('mask.tif'):
                total_tif_files += 1
                file_path = os.path.join(subfolder_path, filename)
                
                # Read the image in grayscale (0 flag)
                mask = cv2.imread(file_path, 0)
                
                if mask is None:
                    print(f"Warning: Could not read file {filename}. Skipping.")
                    continue

                # Calculate pixel counts
                # Assuming 0 is background and anything > 0 is tumor
                total_pixels = mask.size
                tumor_pixels = np.count_nonzero(mask)
                
                # Calculate percentage
                tumor_percentage = (tumor_pixels / total_pixels) * 100
                
                # Check Condition 1: Has tumor (more than 0 pixels)
                if tumor_pixels > 0:
                    files_with_tumor_count += 1
                    
                    # Check Condition 2: Tumor is between 3% and 3.5%
                    # Note: This is nested because a file must have a tumor to be in the range
                    if 3.0 <= tumor_percentage <= 3.5:
                        files_in_range_count += 1
                        # Optional: Print the filename if you want to track specific files
                        # print(f"  [Match] {filename}: {tumor_percentage:.4f}%")

    # --- Report Results ---
    print("-" * 40)
    print("Analysis Complete")
    print("-" * 40)
    print(f"Total .tif files processed:   {total_tif_files}")
    print(f"Files with tumor present:     {files_with_tumor_count}")
    print(f"Files with 3.0%-3.5% tumor:   {files_in_range_count}")
    print("-" * 40)

# --- Usage ---
# Replace 'path/to/your/folder' with the actual path to your .tif files
path = "/home/temi/Downloads/kaggle_3m/"
analyze_tumor_masks(path)