# File entirely generated by Google Gemini 3 (For more info, see report Section 7.1)

from torch.utils.data import DataLoader
from tqdm import tqdm

# Import your dataset class
from pixelDRL.dataset_2d import BraTS2023_Slice_Dataset  

def find_dataset_bounds():
    # 1. Setup Data
    # Use 'train' split to see the full range of data the model was trained on
    PATH_TO_DATASET = "/Dataset001_BraTS2023/"
    dataset = BraTS2023_Slice_Dataset(root_dir=PATH_TO_DATASET, split='train') 
    dataloader = DataLoader(dataset, batch_size=1, num_workers=1, shuffle=False)

    min_val = float('inf')
    max_val = float('-inf')

    print(f"Scanning {len(dataset)} slices to find min/max values...")

    # 2. Loop through batches
    # We don't need gradients or the model, just the data
    for images, _, _ in tqdm(dataloader):
        # images shape: [B, 1, H, W]
        current_min = images.min().item()
        current_max = images.max().item()

        if current_min < min_val:
            min_val = current_min
        if current_max > max_val:
            max_val = current_max

    print("-" * 30)
    print(f"Global Minimum: {min_val:.4f}")
    print(f"Global Maximum: {max_val:.4f}")
    print("-" * 30)
    
    return min_val, max_val

if __name__ == "__main__":
    find_dataset_bounds()