# File partially generated by Google Gemini 3 (For more info, see report Section 7.1)

import torch
import os
import argparse
import matplotlib.pyplot as plt
import sys 

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from dataset_2d import BraTS2023_Slice_Dataset 

SPLIT = 'val_tiny_ratio'
NOISE_LEVELS = [0, 0.01, 0.1, 0.3, 0.5]
TARGET_IMG_IDX = 40
SAVE_DIR = "vis_noise"

def add_noise(image, noise_std):
    """
    Adds Gaussian noise to the image tensor.
    Assumes image is normalized (approx 0-1 or similar).
    """
    if noise_std == 0:
        return image
    
    # Generate noise with mean 0 and standard deviation = noise_std
    noise = torch.randn_like(image) * noise_std
    noisy_image = image + noise
    
    return noisy_image

def visualize_noise_impact(args):
    print(f"Loading dataset from {args.data_dir}...")
    
    dataset = BraTS2023_Slice_Dataset(root_dir=args.data_dir, split=SPLIT, noise=0.0)
    
    if TARGET_IMG_IDX >= len(dataset):
        print(f"Error: Index {TARGET_IMG_IDX} is out of bounds for dataset size {len(dataset)}")
        return

    image, _, _ = dataset[TARGET_IMG_IDX]
    
    num_plots = len(NOISE_LEVELS)
    plt.figure(figsize=(9, 6)) # Plot 3x2 and each subplot is 3 inches wide and 3 inches tall
    
    for i, sigma in enumerate(NOISE_LEVELS):
        noisy_tensor = add_noise(image, sigma)
        
        noisy_np = noisy_tensor.squeeze().numpy()
        
        plt.subplot(1, num_plots, i + 1)
        
        if sigma == 0:
            plt.title("Original (clean)", fontsize=14)
        else:
            plt.title(f"Noise $\sigma={sigma}$", fontsize=14)
            
        plt.imshow(noisy_np, cmap='gray')
        plt.axis('off')

    os.makedirs(SAVE_DIR, exist_ok=True)
    save_path = os.path.join(SAVE_DIR, f"noise_{TARGET_IMG_IDX}.png")
    
    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"Successfully saved noise visualization to: {save_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--data_dir", type=str, required=True, help="Path to BraTS folder")
    args = parser.parse_args()
    
    visualize_noise_impact(args)