# File entirely generated by Google Gemini 3 (For more info, see report Section 7.1)

import os
import glob
import nibabel as nib
import numpy as np
from tqdm import tqdm

data_dir = "/Dataset001_BraTS2023/imagesTr/"

# Get all segmentation files
label_files = glob.glob(os.path.join(data_dir, "*0003.nii.gz"))
print(f"Found {len(label_files)} patients.")

total_slices = 0
tumor_slices = 0
empty_slices = 0

# Scan files (Use tqdm for a progress bar)
for fpath in tqdm(label_files):
    try:
        # Load the 3D volume
        img_obj = nib.load(fpath)
        data = img_obj.get_fdata()
        
        # Iterate through the valid range you used in training (e.g., 20 to 130)
        # Slices 0-20 and 130-155 are usually empty, so we ignore them anyway.
        for slice_idx in range(20, 135): 
            slice_data = data[:, :, slice_idx]
            
            if np.max(slice_data) > 0:
                tumor_slices += 1
            else:
                empty_slices += 1
            
            total_slices += 1
            
    except Exception as e:
        print(f"Error reading {fpath}: {e}")

# Calculate Ratios
ratio_tumor = (tumor_slices / total_slices) * 100
ratio_empty = (empty_slices / total_slices) * 100

print("-" * 30)
print(f"Total Slices Checked: {total_slices}")
print(f"Slices WITH Tumor:    {tumor_slices} ({ratio_tumor:.2f}%)")
print(f"Slices WITHOUT Tumor: {empty_slices} ({ratio_empty:.2f}%)")
print("-" * 30)
